services:
    GuzzleHttpClient:
        class: GuzzleHttp\Client

    GoogleClient:
        class: Google_Client
        calls:
            - [setAuthConfig, ["%googleCredentialsFile%"]]
            - [setApplicationName, ["%googleApiName%"]]
            - [setScopes, ["%googleAnalyticsAuthUrl%"]]
            - [fetchAccessTokenWithAssertion, ["@=service('GuzzleHttpClient')"]]

    GoogleServiceAnalytics:
        class: Google_Service_Analytics
        arguments: ["@=service('GoogleClient')"]

    AnalyticsService:
        class: GoogleApiBundle\Services\AnalyticsService
        calls:
            - [setService, ["@=service('GoogleServiceAnalytics')"]]
