app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

cron:
    resource: "@CronBundle/Controller/"
    type:     annotation
    prefix:   /cron

front:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /test