# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    setting:
        class: AppBundle\Service\Setting
        arguments: [ "@doctrine.orm.customer_entity_manager" ]
    benchmark:
        class: CronBundle\Service\Benchmark