services:
    setting:
        class: AppBundle\Service\Setting
    XlsExport:
        class: AppBundle\Service\XlsExport
    BaseStatistics:
        class: AppBundle\Service\BaseStatistics
    Report_BlackHorses:
        class: AppBundle\Service\BlackHorses
    Report_StarProducts:
        class: AppBundle\Service\StarProducts
    Report_EndOfList:
        class: AppBundle\Service\EndOfList
    Report_Potentials:
        class: AppBundle\Service\Potentials
    Report_DifficultCases:
        class: AppBundle\Service\DifficultCases