services:
    setting:
        class: AppBundle\Service\Setting
    Report_BlackHorses:
        class: AppBundle\Service\BlackHorses
    Report_StarProducts:
        class: AppBundle\Service\StarProducts